default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  username: <%= ENV['RAILS_MYSQL_DATABASE_USERNAME'] || 'root' %>
  password: <%= ENV['RAILS_MYSQL_DATABASE_PASSWORD'] || 'root' %>
  host: <%= ENV['RAILS_MYSQL_DATABASE__HOST'] || 'localhost' %>

development:
  <<: *default
  database: cloud_funding_app_development
  socket: <%= ENV['RAILS_MYSQL_DATABASE_SOCKET'] || '/tmp/mysql.sock'%>

test:
  <<: *default
  database: cloud_funding_app_test
  socket: <%= ENV['SMARTLOG_DATABASE_SOCKET'] %>